# frozen_string_literal: true

TIMEZONE_GROUPS = [
  { display_name: "Greenwich Mean Time",         abbreviations: [ "GMT" ],        iana: "Etc/GMT",              keywords: [ "gmt", "greenwich", "utc" ] },
  { display_name: "GMT / Irish Standard Time",   abbreviations: [ "GMT", "IST" ], iana: "Europe/Dublin",        keywords: [ "gmt", "ist", "irish", "ireland", "dublin" ] },
  { display_name: "India Standard Time",         abbreviations: [ "IST" ],        iana: "Asia/Kolkata",         keywords: [ "ist", "india", "indian", "kolkata", "mumbai", "delhi", "india standard" ] },
  { display_name: "Israel Standard Time",        abbreviations: [ "IST", "IDT" ], iana: "Asia/Jerusalem",       keywords: [ "ist", "israel", "jerusalem", "idt" ] },
  { display_name: "Eastern Time (US)",           abbreviations: [ "EST", "EDT" ], iana: "America/New_York",     keywords: [ "est", "edt", "eastern", "new york", "us eastern" ] },
  { display_name: "Central Time (US)",           abbreviations: [ "CST", "CDT" ], iana: "America/Chicago",      keywords: [ "cst", "cdt", "central", "chicago", "us central" ] },
  { display_name: "Mountain Time (US)",          abbreviations: [ "MST", "MDT" ], iana: "America/Denver",       keywords: [ "mst", "mdt", "mountain", "denver", "us mountain" ] },
  { display_name: "Pacific Time (US)",           abbreviations: [ "PST", "PDT" ], iana: "America/Los_Angeles",  keywords: [ "pst", "pdt", "pacific", "los angeles", "california", "us pacific" ] },
  { display_name: "Alaska Time",                 abbreviations: [ "AKST", "AKDT" ], iana: "America/Anchorage",    keywords: [ "akst", "akdt", "alaska" ] },
  { display_name: "Hawaii Time",                 abbreviations: [ "HST" ],        iana: "Pacific/Honolulu",     keywords: [ "hst", "hawaii", "honolulu" ] },
  { display_name: "Atlantic Time (Canada)",      abbreviations: [ "AST", "ADT" ], iana: "America/Halifax",      keywords: [ "ast", "adt", "atlantic", "halifax", "canada atlantic" ] },
  { display_name: "Newfoundland Time",           abbreviations: [ "NST", "NDT" ], iana: "America/St_Johns",     keywords: [ "nst", "ndt", "newfoundland" ] },
  { display_name: "British Summer Time",         abbreviations: [ "GMT", "BST" ], iana: "Europe/London",        keywords: [ "bst", "gmt", "british", "london", "uk", "england" ] },
  { display_name: "Central European Time",       abbreviations: [ "CET", "CEST" ], iana: "Europe/Paris",         keywords: [ "cet", "cest", "central european", "paris", "berlin", "rome", "madrid" ] },
  { display_name: "Eastern European Time",       abbreviations: [ "EET", "EEST" ], iana: "Europe/Helsinki",      keywords: [ "eet", "eest", "eastern european", "helsinki", "athens" ] },
  { display_name: "Moscow Time",                 abbreviations: [ "MSK" ],        iana: "Europe/Moscow",        keywords: [ "msk", "moscow", "russia" ] },
  { display_name: "Gulf Standard Time",          abbreviations: [ "GST" ],        iana: "Asia/Dubai",           keywords: [ "gst", "gulf", "dubai", "uae", "abu dhabi" ] },
  { display_name: "Arabia Standard Time",        abbreviations: [ "AST" ],        iana: "Asia/Riyadh",          keywords: [ "ast", "arabia", "riyadh", "saudi" ] },
  { display_name: "Pakistan Standard Time",      abbreviations: [ "PKT" ],        iana: "Asia/Karachi",         keywords: [ "pkt", "pakistan", "karachi" ] },
  { display_name: "Bangladesh Standard Time",    abbreviations: [ "BST" ],        iana: "Asia/Dhaka",           keywords: [ "bst", "bangladesh", "dhaka" ] },
  { display_name: "Indochina Time",              abbreviations: [ "ICT" ],        iana: "Asia/Bangkok",         keywords: [ "ict", "indochina", "bangkok", "thailand", "vietnam" ] },
  { display_name: "China Standard Time",         abbreviations: [ "CST" ],        iana: "Asia/Shanghai",        keywords: [ "cst", "china", "shanghai", "beijing", "chn" ] },
  { display_name: "Japan Standard Time",         abbreviations: [ "JST" ],        iana: "Asia/Tokyo",           keywords: [ "jst", "japan", "tokyo" ] },
  { display_name: "Korea Standard Time",         abbreviations: [ "KST" ],        iana: "Asia/Seoul",           keywords: [ "kst", "korea", "seoul" ] },
  { display_name: "Australian Eastern Time",     abbreviations: [ "AEST", "AEDT" ], iana: "Australia/Sydney",     keywords: [ "aest", "aedt", "australian eastern", "sydney", "melbourne", "australia" ] },
  { display_name: "Australian Central Time",     abbreviations: [ "ACST", "ACDT" ], iana: "Australia/Adelaide",   keywords: [ "acst", "acdt", "australian central", "adelaide" ] },
  { display_name: "Australian Western Time",     abbreviations: [ "AWST" ],       iana: "Australia/Perth",      keywords: [ "awst", "australian western", "perth" ] },
  { display_name: "New Zealand Time",            abbreviations: [ "NZST", "NZDT" ], iana: "Pacific/Auckland",     keywords: [ "nzst", "nzdt", "new zealand", "auckland" ] },
  { display_name: "Singapore Time",              abbreviations: [ "SGT" ],        iana: "Asia/Singapore",       keywords: [ "sgt", "singapore" ] },
  { display_name: "Hong Kong Time",              abbreviations: [ "HKT" ],        iana: "Asia/Hong_Kong",       keywords: [ "hkt", "hong kong", "hongkong" ] },
  { display_name: "West Africa Time",            abbreviations: [ "WAT" ],        iana: "Africa/Lagos",         keywords: [ "wat", "west africa", "lagos", "nigeria" ] },
  { display_name: "East Africa Time",            abbreviations: [ "EAT" ],        iana: "Africa/Nairobi",       keywords: [ "eat", "east africa", "nairobi", "kenya" ] },
  { display_name: "South Africa Time",           abbreviations: [ "SAST" ],       iana: "Africa/Johannesburg",  keywords: [ "sast", "south africa", "johannesburg" ] },
  { display_name: "Brazil Time",                 abbreviations: [ "BRT", "BRST" ], iana: "America/Sao_Paulo",    keywords: [ "brt", "brst", "brazil", "sao paulo", "brasil" ] },
  { display_name: "Argentina Time",              abbreviations: [ "ART" ],        iana: "America/Argentina/Buenos_Aires", keywords: [ "art", "argentina", "buenos aires" ] },
  { display_name: "Colombia Time",               abbreviations: [ "COT" ],        iana: "America/Bogota",       keywords: [ "cot", "colombia", "bogota" ] },
  { display_name: "Peru Time",                   abbreviations: [ "PET" ],        iana: "America/Lima",         keywords: [ "pet", "peru", "lima" ] },
  { display_name: "Venezuela Time",              abbreviations: [ "VET" ],        iana: "America/Caracas",      keywords: [ "vet", "venezuela", "caracas" ] },
  { display_name: "Iran Standard Time",          abbreviations: [ "IRST", "IRDT" ], iana: "Asia/Tehran",          keywords: [ "irst", "irdt", "iran", "tehran" ] },
  { display_name: "Afghanistan Time",            abbreviations: [ "AFT" ],        iana: "Asia/Kabul",           keywords: [ "aft", "afghanistan", "kabul" ] },
  { display_name: "Nepal Time",                  abbreviations: [ "NPT" ],        iana: "Asia/Kathmandu",       keywords: [ "npt", "nepal", "kathmandu" ] },
  { display_name: "Myanmar Time",                abbreviations: [ "MMT" ],        iana: "Asia/Rangoon",         keywords: [ "mmt", "myanmar", "rangoon", "yangon" ] },
  { display_name: "UTC",                         abbreviations: [ "UTC" ],        iana: "Etc/UTC",              keywords: [ "utc", "coordinated universal" ] }
].freeze
